### ISSUE TITLE
Bunq API gives HTTP 500 error (Insufficient authentication)

### ISSUE THREAD

**Issue by nickstrijbos** [wesselt/bunq2ynab#49]
The stack last update was on 2022-05-12 08:29:28 UTC+0200. It stopped working on the 22nd of september. So not sure why the API suddenly stopped working. It worked for more than a full year. 

I just created a new Bunq API key, updated the stack again and it works. So not sure if we can add something where it mails us when de lambda function gives a 500 error on API authentication. 

log output from the function when it didn't update.:
----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
|   timestamp   |                                                                                  message                                                                                   |
|---------------|----------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| 1695665133169 | INIT_START Runtime Version: python:3.8.v26 Runtime Version ARN: arn:aws:lambda:eu-north-1::runtime:81f077a44b32842209c33a8a4ecbe13f17dabc0964eaae632cb27846f04bf85e        |
| 1695665133684 | START RequestId: 4df58b78-fdb9-4a1e-a558-bc76d39050bf Version: $LATEST                                                                                                     |
| 1695665133685 | 2023-09-25 18:05:33,685 | INFO | config.py:80 | read_ssm_config | Reading config from SSM                                                                                  |
| 1695665135113 | 2023-09-25 18:05:35,113 | INFO | credentials.py:1102 | load | Found credentials in environment variables.                                                                  |
| 1695665135396 | 2023-09-25 18:05:35,396 | INFO | lambda_function.py:25 | get_iban_from_event | No request body found                                                                       |
| 1695665135396 | 2023-09-25 18:05:35,396 | INFO | sync.py:58 | populate | Retrieving bunq accounts...                                                                                       |
| 1695665135396 | 2023-09-25 18:05:35,396 | INFO | state.py:32 | load | Fetching SSM state bunq2ynab-state                                                                                   |
| 1695665135553 | 2023-09-25 18:05:35,553 | ERROR | lambda_function.py:62 | lambda_handler | Exception occurred                                                                              |
| 1695665135553 | Traceback (most recent call last):                                                                                                                                         |
| 1695665135553 | File "/var/task/lambda_function.py", line 51, in lambda_handler                                                                                                            |
| 1695665135553 | sync.populate()                                                                                                                                                            |
| 1695665135553 | File "/var/task/lib/sync.py", line 59, in populate                                                                                                                         |
| 1695665135553 | self.bunq_accounts = list(bunq_api.get_accounts())                                                                                                                         |
| 1695665135553 | File "/var/task/lib/bunq_api.py", line 109, in get_accounts                                                                                                                |
| 1695665135553 | for u in [first_value(u) for u in bunq.get("v1/user")]:                                                                                                                    |
| 1695665135553 | File "/var/task/lib/bunq.py", line 206, in get                                                                                                                             |
| 1695665135553 | return call('GET', method)                                                                                                                                                 |
| 1695665135553 | File "/var/task/lib/bunq.py", line 197, in call                                                                                                                            |
| 1695665135553 | raise Exception(result["Error"][0]["error_description"])                                                                                                                   |
| 1695665135553 | Exception: Insufficient authentication.

**Comment by wesselt** [comment]
Goed idee, een mail als het token verlopen is. Ik ga kijken hoe ik dat kan toevoegen.

**Comment by nickstrijbos** [comment]
Het stomme is dat Bunq niet laat zien wanneer de token verlopen is. Weet jij toevallig vanuit de API docs of er een verloopdatum op zit? Als ik moet mee kijken in AWS om iets te kunnen mailen moet je het maar even laten weten!

**Comment by wesselt** [comment]
Volgens mij is de duur van een bunq token niet gedocumenteerd en kunnen zij dit veranderen.

Branch / pull request aangemaakt voor email: https://github.com/wesselt/bunq2ynab/pull/50

Hoe werkt deze voor jou?

**Comment by wesselt** [comment]
Sending an email when an error occurs is now supported

**Comment by nickstrijbos** [comment]
Hey Wesselt! Thanks voor het toevoegen. Moet ik nog iets verder testen in AWS? had een beetje hectische week op werk.

**Comment by wesselt** [comment]
Hoi Nick, de AWS versie staat op: https://serverlessrepo.aws.amazon.com/applications/eu-west-1/991880991323/bunq-ynab-aws-lambda

Javy de Koning werkte deze bij, maar ik denk dat hij geen bunq gebruiker meer is. @javydekoning hoe kan ik de repo bijwerken naar een nieuwe versie?

**Comment by nickstrijbos** [comment]
@wesselt Waarschijnlijk de template yaml aanpassen met extra parameters. Ik zat zelf nog te denken dat een poort keuze ook wel handig kan zijn omdat sommige lokaal op 25 al draaien. En ik gebruik bijvoorbeeld google workspace waarbij ik een relay server heb en username password niet perse nodig zijn. Hier voorbeeld toevoeging van parameters. Deze moeten dan nog wel gedefinieerd worden in de juiste config files in die template.yml

```
Parameters:
  BunqApiToken:
    Type: String
    Description: Your BUNQ API Token
  YnabAccessToken:
    Type: String
    Description: Your YNAB access token
  YnabBudget:
    Type: String
    Description: Name of your YNAB budget (use * for all budgets)
  SMTPServer:
    Type: String
    Description: Your SMTP server, for example smtp.google.com
  SMTPPort:
    Type: string
    Description: Port for the SMTP Server, examples are 25, 465 or 587. Relay servers don't require user or password input most of the time. 
  SMTPUser:
    Type: String
    Description: Your SMTP username
  SMTPPassword:
    Type: String
    Description: Your SMTP password
  SMTPFrom:
    Type: String
    Description: From where you get the mail from bunq2ynab@some.where
  SMTPTo:
    Type: String
    Description: Your SMTP to adress, example@gmail.com
```
